### ISSUE TITLE
v7.4.2 breaks cherry-picking import of DayPicker

### ISSUE THREAD

**Issue by shlomitc** [gpbl/react-day-picker#1017]
**Describe the bug**
since the release of v7.4.2, we started receiving the following error in our projects:
`Module not found: Error: Can't resolve 'react-day-picker/DayPicker'`

**To Reproduce**
simply use the following import statements:
`import DayPicker from 'react-day-picker/DayPicker';`

**Expected behavior**
This used to work up until v7.4.1, so I'd expect this to work and break only in the next major version.

**Additional context**
probably caused by this commit: https://github.com/gpbl/react-day-picker/commit/e1afc17b6b556e9e57f6bc14d87662fb6c875d07

**Comment by gpbl** [comment]
Thanks @shlomitc this should be fixed in `v7.4.4` - please check it out!

**Comment by shlomitc** [comment]
Still failing after Installing v7.4.5 (having "react-day-picker": "^7.4.0" in my dependencies)

**Comment by gpbl** [comment]
Sorry I misread the comment – this is the way to import DayPicker:

```js
import DayPicker from 'react-day-picker';
```
